<?php $list = $this->getWidgetSettings() ?>

<?php if ($list): ?>
    <h3><?php echo $this->__('FAQ Widget:') ?></h3>
    <hr />
    <?php foreach ($list as $faqId): ?>
        <?php $faq = $this->getWidgetCollectionById($faqId) ?>
        <ul>
            <li><?php echo "{$this->__('Id: ')} {$faq->getId()}" ?></li>
            <li><?php echo "{$this->__('Question: ')} {$faq->getQuestion()}" ?></li>
            <li><?php echo "{$this->__('Answer: ')} {$faq->getAnswer()}" ?></li>
            <?php $faq->getIsActive()? $isActive = $this->__('Yes') : $isActive = $this->__('No') ?>
            <li><?php echo "{$this->__('Is Active: ')} {$isActive}" ?></li>
        </ul>
        <hr />
    <?php endforeach; ?>
<?php else: ?>
    <?php echo $this->__('The FAQ Widget List has no records.') ?>
<?php endif; ?>
